
version: 2

models:
    - name: stg_transactions
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The customer key for this table"
            tests:
                - not_null

